apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis-service
    app: demo-voting-app
spec:
  #type: NodePort --> default is ClusterIP
  ports:
    - targetPort: 6379
      port: 6379
#      nodePort: 30008 #30000-32767 --> no nodeport in clusterIP for internal communication
  selector:
    name: redis-pod
    app: demo-voting-app
