apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    name: result-service
    app: demo-voting-app
spec:
  type: LoadBalancer  #NodePort #--> default is ClusterIP and if a cloud is LoadBalancer an no need to nodePort
  ports:
    - targetPort: 80
      port: 80
      #nodePort: 30010 #30000-32767 --> no nodeport in clusterIP for internal communication
  selector:
    name: result-app-pod
    app: demo-voting-app
