apiVersion: v1
kind: Service
metadata:
  name: voting-service
  labels:
    name: voting-service
    app: demo-voting-app
spec:
  type: NodePort #--> default is ClusterIP and if a cloud is LoadBalancer an no need to nodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30009 #30000-32767 --> no nodeport in clusterIP for internal communication
  selector:
    name: voting-app-pod
    app: demo-voting-app
